version: '3.8'

services:
  cover-server:
    image: zhangdashuaibi/cover-server:latest
    container_name: codecoverage-server
    environment:
      - SERVICE_TYPE=server
    ports:
      - "18080:8080" # 指定暴露cover-server的18080作为cover-server访问
    volumes:
      - ./conf:/app/conf
    restart: always

  cover-agent:
    image: zhangdashuaibi/cover-agent:latest
    container_name: codecoverage-agent
    environment:
      - SERVICE_TYPE=agent
      - COVER_ADDR=127.0.0.1:7778 # 插桩的覆盖率代理服务器的地址
    network_mode: "service:cover-server"
    depends_on:
      - cover-server
    volumes:
      - ./conf:/app/conf
    restart: always