networks:
  proxy:
    external: true

services:
  cover-server:
    image: zhangdashuaibi/cover-server:latest
    container_name: codecoverage-server
    environment:
      - SERVICE_TYPE=server
      # 配置 MinIO 相关环境变量，解决 OSS 初始化失败问题 （codecoverage代码里，环境变量 > apollo > 配置文件 > 默认值 ）
      - OSS_ENABLED=true
      - OSS_ENDPOINT=minio-oss:9000
      - OSS_ACCESS_KEY=admin
      - OSS_SECRET_KEY=password123
      - OSS_BUCKET=coverage-reports
      - OSS_SECURE=false
      - LOG_OUTPUT=both
      - LOG_FILE_PATH=/app/logs/cover-server.log
    ports:
      - "18080:8080"
    volumes:
      - ./logs/server:/app/logs
    networks:
      - proxy
    restart: always

  cover-agent:
    image: zhangdashuaibi/cover-agent:latest
    container_name: codecoverage-agent
    environment:
      - SERVICE_TYPE=agent
      - COVER_ADDR=127.0.0.1:7778
      - LOG_OUTPUT=both
      - LOG_FILE_PATH=/app/logs/cover-agent.log
    network_mode: "service:cover-server"
    volumes:
      - ./logs/agent:/app/logs
    depends_on:
      - cover-server
    restart: always
