// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: idl/cover-agent/cover-agent.proto

package coveragent

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitId      string                 `protobuf:"bytes,4,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	BaseCommitId  string                 `protobuf:"bytes,5,opt,name=base_commit_id,json=baseCommitId,proto3" json:"base_commit_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,6,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_idl_cover_agent_cover_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cover_agent_cover_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_idl_cover_agent_cover_agent_proto_rawDescGZIP(), []int{0}
}

func (x *BuildInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BuildInfo) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *BuildInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BuildInfo) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *BuildInfo) GetBaseCommitId() string {
	if x != nil {
		return x.BaseCommitId
	}
	return ""
}

func (x *BuildInfo) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type RegisterSUTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	BuildInfo     *BuildInfo             `protobuf:"bytes,3,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSUTRequest) Reset() {
	*x = RegisterSUTRequest{}
	mi := &file_idl_cover_agent_cover_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSUTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSUTRequest) ProtoMessage() {}

func (x *RegisterSUTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cover_agent_cover_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSUTRequest.ProtoReflect.Descriptor instead.
func (*RegisterSUTRequest) Descriptor() ([]byte, []int) {
	return file_idl_cover_agent_cover_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterSUTRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterSUTRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterSUTRequest) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

type RegisterSUTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSUTResponse) Reset() {
	*x = RegisterSUTResponse{}
	mi := &file_idl_cover_agent_cover_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSUTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSUTResponse) ProtoMessage() {}

func (x *RegisterSUTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cover_agent_cover_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSUTResponse.ProtoReflect.Descriptor instead.
func (*RegisterSUTResponse) Descriptor() ([]byte, []int) {
	return file_idl_cover_agent_cover_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSUTResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterSUTResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_idl_cover_agent_cover_agent_proto protoreflect.FileDescriptor

const file_idl_cover_agent_cover_agent_proto_rawDesc = "" +
	"\n" +
	"!idl/cover-agent/cover-agent.proto\x12\n" +
	"coveragent\x1a\x1cgoogle/api/annotations.proto\"\xb5\x01\n" +
	"\tBuildInfo\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x1b\n" +
	"\tcommit_id\x18\x04 \x01(\tR\bcommitId\x12$\n" +
	"\x0ebase_commit_id\x18\x05 \x01(\tR\fbaseCommitId\x12\x19\n" +
	"\bbuild_id\x18\x06 \x01(\tR\abuildId\"x\n" +
	"\x12RegisterSUTRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x124\n" +
	"\n" +
	"build_info\x18\x03 \x01(\v2\x15.coveragent.BuildInfoR\tbuildInfo\"C\n" +
	"\x13RegisterSUTResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x80\x01\n" +
	"\x0fRegisterService\x12m\n" +
	"\vRegisterSUT\x12\x1e.coveragent.RegisterSUTRequest\x1a\x1f.coveragent.RegisterSUTResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/cover/registerBAZ?github.com/shuaibizhang/codecoverage/idl/cover-agent;coveragentb\x06proto3"

var (
	file_idl_cover_agent_cover_agent_proto_rawDescOnce sync.Once
	file_idl_cover_agent_cover_agent_proto_rawDescData []byte
)

func file_idl_cover_agent_cover_agent_proto_rawDescGZIP() []byte {
	file_idl_cover_agent_cover_agent_proto_rawDescOnce.Do(func() {
		file_idl_cover_agent_cover_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_cover_agent_cover_agent_proto_rawDesc), len(file_idl_cover_agent_cover_agent_proto_rawDesc)))
	})
	return file_idl_cover_agent_cover_agent_proto_rawDescData
}

var file_idl_cover_agent_cover_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_idl_cover_agent_cover_agent_proto_goTypes = []any{
	(*BuildInfo)(nil),           // 0: coveragent.BuildInfo
	(*RegisterSUTRequest)(nil),  // 1: coveragent.RegisterSUTRequest
	(*RegisterSUTResponse)(nil), // 2: coveragent.RegisterSUTResponse
}
var file_idl_cover_agent_cover_agent_proto_depIdxs = []int32{
	0, // 0: coveragent.RegisterSUTRequest.build_info:type_name -> coveragent.BuildInfo
	1, // 1: coveragent.RegisterService.RegisterSUT:input_type -> coveragent.RegisterSUTRequest
	2, // 2: coveragent.RegisterService.RegisterSUT:output_type -> coveragent.RegisterSUTResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_cover_agent_cover_agent_proto_init() }
func file_idl_cover_agent_cover_agent_proto_init() {
	if File_idl_cover_agent_cover_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_cover_agent_cover_agent_proto_rawDesc), len(file_idl_cover_agent_cover_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_cover_agent_cover_agent_proto_goTypes,
		DependencyIndexes: file_idl_cover_agent_cover_agent_proto_depIdxs,
		MessageInfos:      file_idl_cover_agent_cover_agent_proto_msgTypes,
	}.Build()
	File_idl_cover_agent_cover_agent_proto = out.File
	file_idl_cover_agent_cover_agent_proto_goTypes = nil
	file_idl_cover_agent_cover_agent_proto_depIdxs = nil
}
